[[t8code]]
arch = "x86_64"
git-tree-sha1 = "92db542d6f6396855fee5611bd95cbc4eed2c854"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "847017cd233d5feca3e5683542d17798ecd4662245ddaa890d22bd47c71eb076"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v1.6.1+2/t8code.v1.6.1.x86_64-linux-gnu-mpi+mpich.tar.gz"
