[[t8code]]
arch = "x86_64"
git-tree-sha1 = "f97590b25d163ec66a54407cfb4c52318d255995"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "3563131482991b72bb258af19fd2a09c22aa6d49d8b3c36a707f623feeb66ac7"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v1.5.2+0/t8code.v1.5.2.x86_64-linux-gnu-mpi+mpich.tar.gz"
