[[t8code]]
arch = "x86_64"
git-tree-sha1 = "593b8ed41f90aa10d015d6ef2032441fda382f32"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "0413dac63e9bba5c9b27c9a7850377b7946860956db538290849c47acd3a130d"
    url = "https://github.com/JuliaBinaryWrappers/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.x86_64-linux-gnu-mpi+mpich.tar.gz"
