[[t8code]]
arch = "x86_64"
git-tree-sha1 = "db9d00b1eaecef9135b00cad5d6d498a16998b17"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "cc76e7345a1f30673093970be94713d5fe43fb76e6acb01ea0237b5d148d0caf"
    url = "https://github.com/JuliaBinaryWrappers/t8code_jll.jl/releases/download/t8code-v4.0.8+0/t8code.v4.0.8.x86_64-linux-gnu-mpi+mpich.tar.gz"
