[[t8code]]
arch = "x86_64"
git-tree-sha1 = "64d586bc38a66e16a3acde92d6d0ba1e22cf89fd"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "b19fe8c562b1f911b252cde5edc8de14c73cd2ee97f16f7a7129f50b372f188d"
    url = "https://github.com/JuliaBinaryWrappers/t8code_jll.jl/releases/download/t8code-v1.6.1+0/t8code.v1.6.1.x86_64-linux-gnu-mpi+mpich.tar.gz"
