[[t8code]]
arch = "x86_64"
git-tree-sha1 = "593b8ed41f90aa10d015d6ef2032441fda382f32"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "a1f03e34fccbdda56e381bc3bb5c52b7917a4aae2afeb68777906f4ccac28ef6"
    url = "https://github.com/JuliaBinaryWrappers/t8code_jll.jl/releases/download/t8code-v4.0.7%2B0/t8code-logs.v4.0.7.x86_64-linux-gnu-mpi+mpich.tar.gz"
